--FOLHA DE EXERCÍCIOS 1 -

--ATIVIDADE 1 -

SELECT *
  FROM TREINA.TBIMOVEL;

SELECT *
  FROM TREINA.TBLOGRADOURO;

SELECT *
  FROM TREINA.TBPESSOA;

SELECT *
  FROM TREINA.TBPESSOACONTATO;

SELECT *
  FROM TREINA.TBPESSOAIMOVEL;

SELECT *
  FROM TREINA.TBTAXA;

/*AATIVIDADE 2*/

SELECT PESCODIGO AS "código da pessoa",
	   CTPNUMERO AS "número de telefone"
 FROM  TREINA.TBPESSOACONTATO;

SELECT IMVCODIGO AS "código do imóvel",
	   IMVLARGURA AS "largura do imóvel",
	   IMVCOMPRIMENTO AS "comprimento do imóvel"
  FROM TREINA.TBIMOVEL;

SELECT PESCODIGO AS "código da pessoa",
	   PESNOME AS "nome da pessoa",
	   PESTIPO AS "tipo da pessoa"
  FROM TREINA.TBPESSOA;

/*ATIVIDADE 3*/

SELECT CTPDESCRICAO
  FROM TREINA.TBPESSOACONTATO
 WHERE TBPESSOACONTATO.CTPDESCRICAO = 'CELULAR';

SELECT PESCODIGO AS "código da pessoa",
	   CTPNUMERO AS "número de telefone"
  FROM TREINA.TBPESSOACONTATO
 WHERE PESCODIGO = 5;

SELECT IMVCODIGO AS "código do imóvel",
	   IMVLARGURA AS "largura do imóvel",
	   IMVCOMPRIMENTO AS "comprimento do imóvel"
  FROM TREINA.TBIMOVEL
 WHERE IMVCOMPRIMENTO >12;

/*ATIVIDADE 4*/

SELECT *
  FROM TREINA.TBPESSOA
 WHERE LOGCODIGO IN (1,7,12);

SELECT *
  FROM TREINA.TBPESSOA
 WHERE PESCODIGO BETWEEN 4 AND 8;

SELECT *
  FROM TREINA.TBPESSOA
 WHERE PESNOME LIKE 'PADARIA';