/*FOLHA DE EXERCÍCIOS 2

ATIVIDADE 1
*/

SELECT CTPNUMERO,CTPDESCRICAO
  FROM TREINA.TBPESSOACONTATO
 WHERE CTPNUMERO LIKE '47%'
   AND CTPDESCRICAO = 'CELULAR';

SELECT LOGTIPO AS "tipo do logradouro",
	   LOGDESCRICAO AS "descrição do logradouro"
  FROM TREINA.TBLOGRADOURO
 WHERE LOGTIPO IN ('RUA','TRAVESSA');

SELECT *
    FROM TREINA.TBPESSOACONTATO
  WHERE CTPRAMAL IS NOT NULL;

--ATIVIDADE 2-

SELECT *
  FROM TREINA.TBPESSOACONTATO
 WHERE CTPDESCRICAO = 'FIXO'
 ORDER BY 2 ASC;

SELECT *
  FROM TREINA.TBIMOVEL
 WHERE IMVDESCRICAO LIKE ‘%CASA DE MADEIRA%’
 ORDER BY 4 DESC;

--ATIVIDADE 3 -

SELECT *
  FROM TREINA.TBPESSOA
 WHERE PESCODIGO BETWEEN 8 AND 12
   AND NOT LOGCODIGO  BETWEEN 4 AND 7;

--ATIVIDADE 4 - 

SELECT * FROM TREINA.TBPESSOA
 LIMIT 5
OFFSET 3;

SELECT * FROM TREINA.TBPESSOA
 WHERE NOT PESNOME LIKE 'P%'
 ORDER BY PESNOME ASC
 LIMIT 3
OFFSET 2;

--ATIVIDADE 5

SELECT MAX(IMVLARGURA * IMVCOMPRIMENTO)
  FROM TREINA.TBIMOVEL;

SELECT COUNT(*)
  FROM TREINA.TBIMOVEL
WHERE IMVDESCRICAO LIKE '%CASA DE MADEIRA%';

SELECT SUM(IMVLARGURA)
   FROM TREINA.TBIMOVEL;

--ATIVIDADE 6 

SELECT IMVCODIGO AS "Código",
       IMVDESCRICAO AS "Descrição",
	   IMVLARGURA AS "Largura",
	   IMVCOMPRIMENTO AS "Comprimento"
	   FROM TREINA.TBIMOVEL
 ORDER BY IMVCODIGO DESC;

SELECT PESCODIGO AS "Código da Pessoa",
       PESNOME AS "Nome da Pessoa"
  FROM TREINA.TBPESSOA
 WHERE PESSEXO = 2
 ORDER BY PESNOME ASC
 LIMIT 4;

--ATIVIDADE 7

SELECT DISTINCT LOGTIPO
  FROM TREINA.TBLOGRADOURO

--ATIVIDADE 8

SELECT COUNT (*) AS “CONTAGEM”, CTPDESCRICAO
  FROM TREINA.TBPESSOACONTATO
 GROUP BY CTPDESCRICAO;