--FOLHA DE EXERCÍCIOS 5

--ATIVIDADE 1-

INSERT INTO TREINA.TBLOGRADOURO
       (logtipo,logdescricao)
VALUES ('TRAVESSA', 'CINCO'),
       ('AVENIDA', 'CINCO'),
       ('AVENIDA', 'SEIS'),
       ('RUA', 'CINCO');

--ATIVIDADE 2 - 

INSERT INTO TREINA.TBPESSOA
       (pesnome,pessexo,pestipo,logcodigo)
VALUES ('ANTONIO WILSON', 1, 1, 13),
       ('ELISANE PORTELA', 2, 1, 14),
       ('FERNANDES DE SOUSA', 1, 1, 15),
       ('MERCEARIA', 3, 2, 16);



--ATIVIDADE 3 -

INSERT INTO TREINA.TBPESSOACONTATO
       (pescodigo,ctpnumero,ctpdescricao,ctpramal)
VALUES (17, '47-99635-1425','CELULAR',NULL),
       (18,'48-98868-3313','CELULAR',NULL),
       (18,'47-99889-2559','CELULAR',NULL),
       (19,'47-3522-1361','FIXO', 258),
       (20,'47-3539-3258','FIXO',NULL);

--ATIVIDADE 4 -

INSERT INTO TREINA.TBIMOVEL
       (IMVDESCRICAO, IMVLARGURA, IMVCOMPRIMENTO, LOGCODIGO)
VALUES ('CASA DE MADEIRA 5', 13, 14, 13),
       ('CASA DE ALVENARIA 5', 15, 19, 14),
       ('CASA DE MADEIRA 6', 14, 15, 15),
       ('CASA DE ALVENARIA 6', 17, 14, 16),
       ('CASA DE MADEIRA 7', 13, 13, 15);
	   
--ATIVIDADE 5 - 

INSERT INTO TREINA.TBPESSOAIMOVEL
       (pescodigo,imvcodigo)
VALUES (17,16),
       (18,17),
       (20,16),
       (20,14);

--ATIVIDADE 6-

INSERT INTO TREINA.TBTAXA
        (PESCODIGO,TAXVALOR,IMVCODIGO)
VALUES (17,321,15),
       (18,1000,17),
       (20,173.80,15),
       (20,0,14);

--ATIVIDADE 7-

--a)

UPDATE TREINA.TBPESSOA
   SET LOGCODIGO = 7
 WHERE PESCODIGO = 3;

--b)

UPDATE TREINA.TBPESSOA
   SET LOGCODIGO = 8
 WHERE PESCODIGO IN (5,7);

--c)

UPDATE TREINA.TBPESSOACONTATO
   SET CTPDESCRICAO = 'TELEFONE FIXO'
 WHERE CTPDESCRICAO = 'FIXO';



--d)

UPDATE TREINA.TBIMOVEL
   SET IMVLARGURA = 14, IMVCOMPRIMENTO = 14
 WHERE IMVCODIGO = 8;


--ATIVIDADE 8 - 

--a)

DELETE FROM TREINA.TBIMOVEL
 WHERE IMVDESCRICAO LIKE '%MADEIRA%'
   AND IMVLARGURA > 15;

--b)

DELETE FROM TREINA.TBPESSOACONTATO
 WHERE CTPRAMAL = 1537;
